### ISSUE TITLE
Solve breaks down for low w_0/gamma in oscillator.py

### ISSUE THREAD

**Issue by sandeshkalantre** [sandeshkalantre/waves#1]
I tried adding the epsilon to RHS but the problem could not solved. Suggestions are welcome to mitigate the problem in this integration scheme (RK4).

Or maybe we can change the integration scheme?

**Comment by cheekujodhpur** [comment]
This is how the first few lines look for a linspace of 100 s with 100 points, epsilon set to 1e-15 

[2.          0.        ]
 [ 0.65819661  9.38630051]
 [-1.54544133  6.19565181]
 [-1.67168715 -5.20237863]
 [ 0.42647238 -9.56733948]
 [ 1.93638985 -1.16505651]

With a linspace of 500 s with 100 points however
[  2.00000000e+00   0.00000000e+00]
 [  1.93638985e+00  -1.16505651e+00]
 [  1.84765569e+00  -2.25573280e+00]
 [  1.73632975e+00  -3.25977532e+00]
 [  1.60514912e+00  -4.16680020e+00]
 [  1.45700615e+00  -4.96834881e+00]
...

And you'll see by the latest commit that this gives good results, "good looking results" which are **wrong**, we're overestimating gamma when we take larger time sample.

I made a mistake of thinking this has nothing to do with epsilon and I was wrong. I reverted that commit. 

Here is my **current hypothesis** to be explored later:
RK4 "overshoots" or whatever you call that when the update value is supposed to be incredibly small as in the case with low gamma. Thus, only for larger time samples, we get good results.

As far as using epsilon is concerned, it really means 0 for the machine. Having it does improve results as it should. It does not work perfectly because we have problems inherent to RK4, in my belief

**Comment by sandeshkalantre** [comment]
Also the RK4 solver seems to go bad for low gamma and high w_0 (gamma=0.01, w_0 = 50)j. This issue can resolved by increasing the number of points. 

What scaling of the number of points do you suggest based on w_0 and gamma values?

**Comment by cheekujodhpur** [comment]
Aliasing error. Have ~10 points per seconds as an adhoc solution
